# -*- coding: utf-8 -*-
"""CKA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nGK9XjLlHzmaX-2LAUKe5vM3P2achaDc
"""

# ================================
# 1. Setup
# ================================
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# ================================
# 2. Dataset
# ================================
transform = transforms.Compose([
    transforms.Resize((32, 32)),
    transforms.ToTensor(),
])

trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                        download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=128, shuffle=True)

testset = torchvision.datasets.CIFAR10(root='./data', train=False,
                                       download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=128, shuffle=False)

# ================================
# 3. MSB-CNN Model
# ================================
class MSB_CNN(nn.Module):
    def __init__(self, c1, c2, c3):
        super().__init__()

        self.stage1 = nn.Sequential(
            nn.Conv2d(3, 16, 3, padding=1),
            nn.ReLU(),
            nn.Conv2d(16, c1, 3, padding=1),
            nn.ReLU()
        )

        self.stage2 = nn.Sequential(
            nn.Conv2d(c1, 32, 3, padding=1),
            nn.ReLU(),
            nn.Conv2d(32, c2, 3, padding=1),
            nn.ReLU()
        )

        self.stage3 = nn.Sequential(
            nn.Conv2d(c2, 64, 3, padding=1),
            nn.ReLU(),
            nn.Conv2d(64, c3, 3, padding=1),
            nn.ReLU()
        )

        self.pool = nn.AdaptiveAvgPool2d((1,1))
        self.fc = nn.Linear(c3, 10)

    def forward(self, x):
        a1 = self.stage1(x)
        a2 = self.stage2(a1)
        a3 = self.stage3(a2)

        out = self.pool(a3)
        out = out.view(out.size(0), -1)
        out = self.fc(out)

        return out, [a1, a2, a3]

# ================================
# 4. Training
# ================================
def train_model(model, epochs=5):
    model.to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=0.001)

    for epoch in range(epochs):
        model.train()
        total_loss = 0

        for images, labels in trainloader:
            images, labels = images.to(device), labels.to(device)

            optimizer.zero_grad()
            outputs, _ = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}")

    return model

# ================================
# 5. Evaluation
# ================================
def evaluate(model):
    model.eval()
    correct, total = 0, 0

    with torch.no_grad():
        for images, labels in testloader:
            images, labels = images.to(device), labels.to(device)

            outputs, _ = model(images)
            _, predicted = torch.max(outputs, 1)

            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    return 100 * correct / total

# ================================
# 6. CKA FUNCTIONS
# ================================
def gram_linear(x):
    return x @ x.T

def center_gram(g):
    n = g.size(0)
    H = torch.eye(n, device=g.device) - torch.ones(n, n, device=g.device)/n
    return H @ g @ H

def cka(x, y):
    K = center_gram(gram_linear(x))
    L = center_gram(gram_linear(y))
    return (K * L).sum() / (torch.norm(K) * torch.norm(L))

# ================================
# 7. Compute CKA
# ================================
def compute_cka_matrix(model):
    model.eval()

    images, _ = next(iter(testloader))
    images = images.to(device)

    _, activations = model(images)

    # Flatten spatial dims
    activations = [a.mean(dim=[2,3]) for a in activations]

    n = len(activations)
    cka_matrix = torch.zeros(n, n)

    for i in range(n):
        for j in range(n):
            cka_matrix[i, j] = cka(activations[i], activations[j]).item()

    return cka_matrix

# ================================
# 8. Train ONE Model (Progressive)
# ================================
print("\nTraining Progressive Model...")
model = MSB_CNN(8, 32, 128)
model = train_model(model, epochs=5)

acc = evaluate(model)
print(f"Accuracy: {acc:.2f}%")

# ================================
# 9. Compute & Plot CKA
# ================================
cka_mat = compute_cka_matrix(model)

plt.figure()
plt.imshow(cka_mat.numpy())
plt.colorbar()
plt.title("CKA Similarity Between Layers")
plt.xlabel("Layer")
plt.ylabel("Layer")
plt.show()