# -*- coding: utf-8 -*-
"""Ganglion Filters.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nGK9XjLlHzmaX-2LAUKe5vM3P2achaDc
"""

import numpy as np
import matplotlib.pyplot as plt
import torch

########################################
# Settings
########################################

IMG_SIZE = 32
NUM_STIMULI = 20

########################################
# Difference of Gaussian (DoG)
# Retina Ganglion Model
########################################

def dog_filter(size, sigma_c=1.5, sigma_s=4):

    ax = np.linspace(-(size//2), size//2, size)
    xx, yy = np.meshgrid(ax, ax)

    center = np.exp(-(xx**2 + yy**2)/(2*sigma_c**2))
    surround = np.exp(-(xx**2 + yy**2)/(2*sigma_s**2))

    dog = center - surround
    return dog

########################################
# Generate Ganglion Filters
########################################

dog = dog_filter(IMG_SIZE)

plt.figure(figsize=(4,4))
plt.imshow(dog, cmap="seismic")
#plt.title("Ganglion Cell Receptive Field (DoG)")
plt.colorbar()
plt.show()

########################################
# Generate Random Stimuli
########################################

stimuli = np.random.randn(NUM_STIMULI, IMG_SIZE, IMG_SIZE)

########################################
# Compute Ganglion Responses
########################################

responses = []

for stim in stimuli:

    response = np.convolve(stim.flatten(), dog.flatten(), mode='same')
    response = response.reshape(IMG_SIZE, IMG_SIZE)

    responses.append(response)

responses = np.array(responses)

########################################
# Visualize Input Stimuli
########################################

plt.figure(figsize=(8,5))

for i in range(6):
    plt.subplot(2,3,i+1)
    plt.imshow(stimuli[i], cmap="gray")
    plt.title("Stimulus")
    plt.axis("off")

plt.suptitle("Input Stimuli")
plt.show()

########################################
# Visualize Ganglion Responses
########################################

plt.figure(figsize=(8,5))

for i in range(6):
    plt.subplot(2,3,i+1)
    plt.imshow(responses[i], cmap="seismic")
    plt.title("Ganglion Response")
    plt.axis("off")

plt.suptitle("Ganglion Cell Responses")
plt.show()

########################################
# Convert to PyTorch Tensor
########################################

ganglion_inputs = torch.tensor(responses).unsqueeze(1).float()

print("Ganglion Input Shape:", ganglion_inputs.shape)