# -*- coding: utf-8 -*-
"""MSB-CNN + ResNet + CKA .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nGK9XjLlHzmaX-2LAUKe5vM3P2achaDc
"""

# ================================
# 1. Setup
# ================================
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
import torchvision.models as models
import matplotlib.pyplot as plt

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# ================================
# 2. Dataset
# ================================
transform = transforms.Compose([
    transforms.Resize((32, 32)),
    transforms.ToTensor(),
])

trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                        download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=128, shuffle=True)

testset = torchvision.datasets.CIFAR10(root='./data', train=False,
                                       download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=128, shuffle=False)

# ================================
# 3. MSB-CNN Model
# ================================
class MSB_CNN(nn.Module):
    def __init__(self, c1, c2, c3):
        super().__init__()

        self.stage1 = nn.Sequential(
            nn.Conv2d(3, 16, 3, padding=1),
            nn.ReLU(),
            nn.Conv2d(16, c1, 3, padding=1),
            nn.ReLU()
        )

        self.stage2 = nn.Sequential(
            nn.Conv2d(c1, 32, 3, padding=1),
            nn.ReLU(),
            nn.Conv2d(32, c2, 3, padding=1),
            nn.ReLU()
        )

        self.stage3 = nn.Sequential(
            nn.Conv2d(c2, 64, 3, padding=1),
            nn.ReLU(),
            nn.Conv2d(64, c3, 3, padding=1),
            nn.ReLU()
        )

        self.pool = nn.AdaptiveAvgPool2d((1,1))
        self.fc = nn.Linear(c3, 10)

    def forward(self, x):
        a1 = self.stage1(x)
        a2 = self.stage2(a1)
        a3 = self.stage3(a2)

        out = self.pool(a3)
        out = out.view(out.size(0), -1)
        out = self.fc(out)

        return out, [a1, a2, a3]

# ================================
# 4. ResNet Model
# ================================
def get_resnet():
    model = models.resnet18(num_classes=10)
    return model

# ================================
# 5. Training
# ================================
def train_model(model, epochs=5, return_acts=False):
    model.to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=0.001)

    for epoch in range(epochs):
        model.train()
        total_loss = 0

        for images, labels in trainloader:
            images, labels = images.to(device), labels.to(device)

            optimizer.zero_grad()

            if return_acts:
                outputs, _ = model(images)
            else:
                outputs = model(images)

            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}")

    return model

# ================================
# 6. Evaluation
# ================================
def evaluate(model, return_acts=False):
    model.eval()
    correct, total = 0, 0

    with torch.no_grad():
        for images, labels in testloader:
            images, labels = images.to(device), labels.to(device)

            if return_acts:
                outputs, _ = model(images)
            else:
                outputs = model(images)

            _, predicted = torch.max(outputs, 1)

            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    return 100 * correct / total

# ================================
# 7. CKA Functions
# ================================
def gram(x):
    return x @ x.T

def center(g):
    n = g.size(0)
    H = torch.eye(n, device=g.device) - torch.ones(n,n,device=g.device)/n
    return H @ g @ H

def cka(x, y):
    K = center(gram(x))
    L = center(gram(y))
    return (K*L).sum() / (torch.norm(K)*torch.norm(L))

def compute_cka(model):
    model.eval()
    images, _ = next(iter(testloader))
    images = images.to(device)

    _, acts = model(images)
    acts = [a.mean(dim=[2,3]) for a in acts]

    n = len(acts)
    mat = torch.zeros(n,n)

    for i in range(n):
        for j in range(n):
            mat[i,j] = cka(acts[i], acts[j]).item()

    return mat

# ================================
# 8. Feature Visualization
# ================================
def visualize_features(model):
    model.eval()
    images, _ = next(iter(testloader))
    images = images.to(device)

    _, acts = model(images[:1])

    for i, act in enumerate(acts):
        fmap = act[0].cpu()

        plt.figure(figsize=(10,2))
        for j in range(min(8, fmap.shape[0])):
            plt.subplot(1,8,j+1)
            plt.imshow(fmap[j], cmap='gray')
            plt.axis('off')

        plt.suptitle(f"Stage {i+1} Features")
        plt.show()

# ================================
# 9. Run Experiments
# ================================
configs = {
    "Tight": (4, 8, 16),
    "Progressive": (8, 32, 128),
    "Regressive": (128, 32, 8),
    "Wide": (32, 64, 128)
}

results = {}

# Train MSB-CNN variants
for name, (c1, c2, c3) in configs.items():
    print(f"\nTraining {name}...")
    model = MSB_CNN(c1, c2, c3)
    model = train_model(model, return_acts=True)

    acc = evaluate(model, return_acts=True)
    results[name] = {"accuracy": acc, "model": model}

# Train ResNet
print("\nTraining ResNet...")
resnet = get_resnet().to(device)
resnet = train_model(resnet)

acc = evaluate(resnet)
results["ResNet18"] = {"accuracy": acc, "model": resnet}

# ================================
# 10. Accuracy Plot
# ================================
names = list(results.keys())
accs = [results[k]["accuracy"] for k in names]

plt.figure()
plt.bar(names, accs)
plt.title("Accuracy Comparison (MSB-CNN vs ResNet)")
plt.ylabel("Accuracy (%)")
plt.xticks(rotation=30)
plt.show()

# ================================
# 11. CKA Plot (Progressive)
# ================================
print("\nComputing CKA for Progressive model...")
cka_mat = compute_cka(results["Progressive"]["model"])

plt.figure()
plt.imshow(cka_mat.numpy())
plt.colorbar()
plt.title("CKA Similarity (Progressive)")
plt.show()

# ================================
# 12. Feature Visualization
# ================================
print("\nVisualizing Features...")
visualize_features(results["Progressive"]["model"])

# ================================
# 13. Print Results
# ================================
print("\nFinal Results:")
for k, v in results.items():
    print(f"{k}: {v['accuracy']:.2f}%")