# -*- coding: utf-8 -*-
"""Retinal Ganglion Cell Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nGK9XjLlHzmaX-2LAUKe5vM3P2achaDc
"""

import torch
import torch.nn as nn
import numpy as np
import random
import matplotlib.pyplot as plt
from torch.utils.data import Dataset, DataLoader, random_split
import torch.nn.functional as F

########################################
# Settings
########################################

IMG_SIZE = 32
DATASET_SIZE = 5000
BATCH_SIZE = 128
EPOCHS = 4

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

########################################
# Seed
########################################

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

set_seed()

########################################
# Retinal Ganglion Model (DoG)
########################################

def dog_kernel(size=9, sigma_c=1.5, sigma_s=3):

    ax = np.linspace(-(size//2), size//2, size)
    xx, yy = np.meshgrid(ax, ax)

    center = np.exp(-(xx**2 + yy**2)/(2*sigma_c**2))
    surround = np.exp(-(xx**2 + yy**2)/(2*sigma_s**2))

    dog = center - surround
    dog = dog / np.sum(np.abs(dog))

    kernel = torch.tensor(dog).float().unsqueeze(0).unsqueeze(0)

    return kernel

dog = dog_kernel().to(device)

def retinal_layer(x):
    return F.conv2d(x, dog, padding=4)

########################################
# Stimulus Generation
########################################

def generate_stimuli():

    freqs=[2,4,8]
    thetas=np.arange(0,180,20)
    phases=[0,0.5]

    x=np.arange(IMG_SIZE)
    y=np.arange(IMG_SIZE)
    xv,yv=np.meshgrid(x,y)

    stimuli=[]

    for f in freqs:
        for t in thetas:
            theta=np.deg2rad(t)
            for p in phases:
                img=np.sin(
                    2*np.pi*f*(xv*np.cos(theta)+yv*np.sin(theta))/IMG_SIZE + p
                )
                stimuli.append(img)

    stimuli=np.array(stimuli).astype(np.float32)
    stimuli=torch.tensor(stimuli).unsqueeze(1)

    return stimuli

stimuli = generate_stimuli().to(device)

########################################
# Retinal Responses
########################################

with torch.no_grad():
    stimuli_retina = retinal_layer(stimuli)

########################################
# Visualize Stimulus Pipeline
########################################

plt.figure(figsize=(10,4))

for i in range(6):

    plt.subplot(2,6,i+1)
    plt.imshow(stimuli[i,0].cpu(), cmap="gray")
    plt.title("Stimulus")
    plt.axis("off")

    plt.subplot(2,6,i+7)
    plt.imshow(stimuli_retina[i,0].cpu(), cmap="seismic")
    plt.title("Retina")
    plt.axis("off")

plt.suptitle("Stimulus → Retinal Ganglion Response")
plt.show()

########################################
# Dataset
########################################

class VisionDataset(Dataset):

    def __init__(self,n=DATASET_SIZE):

        x=np.random.randn(n,IMG_SIZE,IMG_SIZE).astype(np.float32)
        labels=np.random.randint(0,3,n)

        x=torch.tensor(x).unsqueeze(1)

        with torch.no_grad():
            x=retinal_layer(x)

        self.x=x
        self.y=torch.tensor(labels)

    def __len__(self):
        return len(self.x)

    def __getitem__(self,idx):
        return self.x[idx],self.y[idx]

dataset=VisionDataset()

########################################
# Visualize Dataset Inputs
########################################

plt.figure(figsize=(10,4))

for i in range(6):

    img,label=dataset[i]

    plt.subplot(2,6,i+1)
    plt.imshow(img[0],cmap="seismic")
    plt.title("Retina Input")
    plt.axis("off")

plt.suptitle("Training Inputs (Retinal Responses)")
plt.show()

########################################
# DataLoader
########################################

train_size=int(0.8*len(dataset))
test_size=len(dataset)-train_size
train_ds,test_ds=random_split(dataset,[train_size,test_size])

train_loader=DataLoader(train_ds,batch_size=BATCH_SIZE,shuffle=True)

########################################
# Model
########################################

class MSBCNN(nn.Module):

    def __init__(self,width):
        super().__init__()

        c1=width
        c2=width*2
        c3=width*4

        self.stage1=nn.Sequential(
            nn.Conv2d(1,16,3,padding=1),
            nn.ReLU(),
            nn.Conv2d(16,c1,3,padding=1),
            nn.ReLU()
        )

        self.stage2=nn.Sequential(
            nn.Conv2d(c1,32,3,padding=1),
            nn.ReLU(),
            nn.Conv2d(32,c2,3,padding=1),
            nn.ReLU()
        )

        self.stage3=nn.Sequential(
            nn.Conv2d(c2,64,3,padding=1),
            nn.ReLU(),
            nn.Conv2d(64,c3,3,padding=1),
            nn.ReLU()
        )

        self.pool=nn.AdaptiveAvgPool2d(1)
        self.fc=nn.Linear(c3,3)

    def forward(self,x):

        s1=self.stage1(x)
        s2=self.stage2(s1)
        s3=self.stage3(s2)

        out=self.pool(s3).view(x.size(0),-1)
        out=self.fc(out)

        return out,s1,s2,s3

########################################
# Feature Map Visualization
########################################

def visualize_feature_maps(feature_maps,title):

    fm=feature_maps[0].cpu().detach()

    plt.figure(figsize=(8,4))

    for i in range(min(8,fm.shape[0])):

        plt.subplot(2,4,i+1)
        plt.imshow(fm[i],cmap="viridis")
        plt.axis("off")

    plt.suptitle(title)
    plt.show()

########################################
# Training
########################################

def train(model):

    opt=torch.optim.Adam(model.parameters(),lr=1e-3)
    loss_fn=nn.CrossEntropyLoss()

    model.train()

    for epoch in range(EPOCHS):

        total=0

        for x,y in train_loader:

            x,y=x.to(device),y.to(device)

            opt.zero_grad()

            out,_,_,_=model(x)

            loss=loss_fn(out,y)

            loss.backward()

            opt.step()

            total+=loss.item()

        print("Epoch",epoch+1,"Loss:",total)

########################################
# Opponency
########################################

def opponency(stage):

    acts=stage.mean(dim=(2,3)).cpu().numpy()

    baseline=acts.mean(axis=0)
    delta=0.1*(acts.max(axis=0)-acts.min(axis=0))

    opp=((acts.max(axis=0)>baseline+delta)&
         (acts.min(axis=0)<baseline-delta))

    return opp.mean()

########################################
# Scaling Experiment
########################################

widths=[4,8,16,32]

stage1_results=[]
stage2_results=[]
stage3_results=[]

for w in widths:

    print("\nTraining width:",w)

    model=MSBCNN(w).to(device)

    train(model)

    with torch.no_grad():

        out,s1,s2,s3=model(stimuli_retina)

    visualize_feature_maps(s1,"Stage 1 Feature Maps")
    visualize_feature_maps(s2,"Stage 2 Feature Maps")
    visualize_feature_maps(s3,"Stage 3 Feature Maps")

    stage1_results.append(opponency(s1))
    stage2_results.append(opponency(s2))
    stage3_results.append(opponency(s3))

########################################
# Plot Scaling
########################################

plt.figure(figsize=(7,5))

plt.plot(widths,stage1_results,'o-',label="Stage 1")
plt.plot(widths,stage2_results,'o-',label="Stage 2")
plt.plot(widths,stage3_results,'o-',label="Stage 3")

plt.xlabel("Network Width")
plt.ylabel("Opponent Neuron Fraction")
plt.title("Scaling of Opponency (Retinal Input)")
plt.legend()
plt.show()