# -*- coding: utf-8 -*-
"""Sinusoidal Stimuli.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nGK9XjLlHzmaX-2LAUKe5vM3P2achaDc
"""

import torch
import torch.nn as nn
import numpy as np
import random
import matplotlib.pyplot as plt
from torch.utils.data import Dataset, DataLoader, random_split

########################################
# Settings
########################################

IMG_SIZE = 32
DATASET_SIZE = 5000
BATCH_SIZE = 128
EPOCHS = 4

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

########################################
# Seed
########################################

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

set_seed()

########################################
# Stimuli Generation
########################################

def generate_stimuli():

    freqs=[2,4,8]
    thetas=np.arange(0,180,20)
    phases=[0,0.5]

    x=np.arange(IMG_SIZE)
    y=np.arange(IMG_SIZE)
    xv,yv=np.meshgrid(x,y)

    stimuli=[]

    for f in freqs:
        for t in thetas:
            theta=np.deg2rad(t)
            for p in phases:
                img=np.sin(
                    2*np.pi*f*(xv*np.cos(theta)+yv*np.sin(theta))/IMG_SIZE + p
                )
                stimuli.append(img)

    stimuli=np.array(stimuli).astype(np.float32)
    return torch.tensor(stimuli).unsqueeze(1)

stimuli = generate_stimuli().to(device)

########################################
# Visualize Stimuli
########################################

plt.figure(figsize=(8,6))
for i in range(12):
    plt.subplot(3,4,i+1)
    plt.imshow(stimuli[i,0].cpu(), cmap="gray")
    plt.axis("off")
plt.suptitle("Example Sinusoidal Stimuli")
plt.show()

########################################
# Dataset
########################################

class VisionDataset(Dataset):

    def __init__(self,n=DATASET_SIZE):

        x=np.random.randn(n,IMG_SIZE,IMG_SIZE).astype(np.float32)
        labels=np.random.randint(0,3,n)

        self.x=torch.tensor(x).unsqueeze(1)
        self.y=torch.tensor(labels)

    def __len__(self):
        return len(self.x)

    def __getitem__(self,idx):
        return self.x[idx],self.y[idx]

dataset=VisionDataset()

########################################
# Visualize Training Images
########################################

plt.figure(figsize=(8,6))
for i in range(12):
    img,_=dataset[i]
    plt.subplot(3,4,i+1)
    plt.imshow(img[0],cmap="gray")
    plt.axis("off")
plt.suptitle("Example Training Inputs")
plt.show()

########################################
# DataLoader
########################################

train_size=int(0.8*len(dataset))
test_size=len(dataset)-train_size
train_ds,test_ds=random_split(dataset,[train_size,test_size])

train_loader=DataLoader(
    train_ds,
    batch_size=BATCH_SIZE,
    shuffle=True
)

########################################
# Model
########################################

class MSBCNN(nn.Module):

    def __init__(self,width):
        super().__init__()

        c1=width
        c2=width*2
        c3=width*4

        self.stage1=nn.Sequential(
            nn.Conv2d(1,16,3,padding=1),
            nn.ReLU(),
            nn.Conv2d(16,c1,3,padding=1),
            nn.ReLU()
        )

        self.stage2=nn.Sequential(
            nn.Conv2d(c1,32,3,padding=1),
            nn.ReLU(),
            nn.Conv2d(32,c2,3,padding=1),
            nn.ReLU()
        )

        self.stage3=nn.Sequential(
            nn.Conv2d(c2,64,3,padding=1),
            nn.ReLU(),
            nn.Conv2d(64,c3,3,padding=1),
            nn.ReLU()
        )

        self.pool=nn.AdaptiveAvgPool2d(1)
        self.fc=nn.Linear(c3,3)

    def forward(self,x):

        s1=self.stage1(x)
        s2=self.stage2(s1)
        s3=self.stage3(s2)

        out=self.pool(s3).view(x.size(0),-1)
        out=self.fc(out)

        return out,s1,s2,s3

########################################
# Training
########################################

def train(model):

    opt=torch.optim.Adam(model.parameters(),lr=1e-3)
    loss_fn=nn.CrossEntropyLoss()

    model.train()

    for epoch in range(EPOCHS):

        total=0

        for x,y in train_loader:
            x,y=x.to(device),y.to(device)

            opt.zero_grad()
            out,_,_,_=model(x)
            loss=loss_fn(out,y)
            loss.backward()
            opt.step()

            total+=loss.item()

        print("Epoch",epoch+1,"Loss:",total)

########################################
# Feature Map Visualization
########################################

def visualize_feature_maps(feature_maps, title):

    feature_maps = feature_maps[0].cpu().detach()

    plt.figure(figsize=(10,5))

    for i in range(min(8, feature_maps.shape[0])):
        plt.subplot(2,4,i+1)
        plt.imshow(feature_maps[i], cmap='viridis')
        plt.axis("off")

    plt.suptitle(title)
    plt.show()

########################################
# Opponency
########################################

def opponency(stage):

    acts=stage.mean(dim=(2,3)).cpu().numpy()

    baseline=acts.mean(axis=0)
    delta=0.1*(acts.max(axis=0)-acts.min(axis=0))

    opp=((acts.max(axis=0)>baseline+delta) &
         (acts.min(axis=0)<baseline-delta))

    return opp.mean()

########################################
# Scaling Experiment
########################################

widths=[4,8,16,32,64]

stage1_results=[]
stage2_results=[]
stage3_results=[]

for w in widths:

    print("\nTraining model with width:",w)

    model=MSBCNN(w).to(device)

    train(model)

    with torch.no_grad():

        out,s1,s2,s3=model(stimuli)

    visualize_feature_maps(s1,"Stage 1 Feature Maps")
    visualize_feature_maps(s2,"Stage 2 Feature Maps")
    visualize_feature_maps(s3,"Stage 3 Feature Maps")

    stage1_results.append(opponency(s1))
    stage2_results.append(opponency(s2))
    stage3_results.append(opponency(s3))

########################################
# Plot Scaling Law
########################################

plt.figure(figsize=(7,5))

plt.plot(widths,stage1_results,marker="o",label="Stage 1")
plt.plot(widths,stage2_results,marker="o",label="Stage 2")
plt.plot(widths,stage3_results,marker="o",label="Stage 3")

plt.xlabel("Network Width")
plt.ylabel("Opponent Neuron Fraction")
plt.title("Scaling Law of Opponency")
plt.legend()
plt.show()