# -*- coding: utf-8 -*-
"""Validation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U3fnYo8_yxnRGmmuZW4ae_Wb_YeWRftL
"""

# Progressive vs Regressive vs Uniform ResNet18
#====================================================
#
# 1. CIFAR-10
# 2. CIFAR-100
# 3. Tiny-ImageNet
# 4. Accuracy comparison
# 5. CKA analysis
# 6. Representation analysis
# 7. PCA feature visualization
# 8. Feature map visualization
# 9. Publication-quality plots



!pip install -q torch torchvision tqdm scikit-learn seaborn

# ============================================================
# 2. IMPORTS
# ============================================================

import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from tqdm import tqdm
from sklearn.decomposition import PCA

import torch
import torch.nn as nn
import torch.optim as optim

import torchvision
import torchvision.transforms as transforms
import torchvision.models as models

from torchvision import datasets
from torch.utils.data import DataLoader

# ============================================================
# 3. DEVICE
# ============================================================

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Using device:", device)

# ============================================================
# 4. DATASET CONFIG
# ============================================================

#DATASET = "cifar100"
DATASET = "tinyimagenet"
# DATASET = "cifar10"

BATCH_SIZE = 128
EPOCHS = 20
LR = 0.001

# ============================================================
# 5. DATASET LOADER
# ============================================================

def get_dataloaders(dataset_name):

    # --------------------------------------------------------
    # CIFAR-10
    # --------------------------------------------------------

    if dataset_name == "cifar10":

        transform_train = transforms.Compose([
            transforms.RandomCrop(32, padding=4),
            transforms.RandomHorizontalFlip(),
            transforms.ToTensor(),
        ])

        transform_test = transforms.Compose([
            transforms.ToTensor(),
        ])

        trainset = torchvision.datasets.CIFAR10(
            root='./data',
            train=True,
            download=True,
            transform=transform_train
        )

        testset = torchvision.datasets.CIFAR10(
            root='./data',
            train=False,
            download=True,
            transform=transform_test
        )

        num_classes = 10

    # --------------------------------------------------------
    # CIFAR-100
    # --------------------------------------------------------

    elif dataset_name == "cifar100":

        transform_train = transforms.Compose([
            transforms.RandomCrop(32, padding=4),
            transforms.RandomHorizontalFlip(),
            transforms.ToTensor(),
        ])

        transform_test = transforms.Compose([
            transforms.ToTensor(),
        ])

        trainset = torchvision.datasets.CIFAR100(
            root='./data',
            train=True,
            download=True,
            transform=transform_train
        )

        testset = torchvision.datasets.CIFAR100(
            root='./data',
            train=False,
            download=True,
            transform=transform_test
        )

        num_classes = 100

    # --------------------------------------------------------
    # TINY-IMAGENET
    # --------------------------------------------------------

    elif dataset_name == "tinyimagenet":

        if not os.path.exists("tiny-imagenet-200"):

            !wget http://cs231n.stanford.edu/tiny-imagenet-200.zip
            !unzip -q tiny-imagenet-200.zip

        transform_train = transforms.Compose([
            transforms.RandomCrop(64, padding=4),
            transforms.RandomHorizontalFlip(),
            transforms.ToTensor(),
        ])

        transform_test = transforms.Compose([
            transforms.ToTensor(),
        ])

        trainset = datasets.ImageFolder(
            './tiny-imagenet-200/train',
            transform=transform_train
        )

        testset = datasets.ImageFolder(
            './tiny-imagenet-200/val',
            transform=transform_test
        )

        num_classes = 200

    trainloader = DataLoader(
        trainset,
        batch_size=BATCH_SIZE,
        shuffle=True,
        num_workers=2
    )

    testloader = DataLoader(
        testset,
        batch_size=BATCH_SIZE,
        shuffle=False,
        num_workers=2
    )

    return trainloader, testloader, num_classes

# ============================================================
# 6. BOTTLENECK RESNET18
# ============================================================

class BasicBlock(nn.Module):

    expansion = 1

    def __init__(self, in_channels, out_channels, stride=1):

        super().__init__()

        self.conv1 = nn.Conv2d(
            in_channels,
            out_channels,
            kernel_size=3,
            stride=stride,
            padding=1,
            bias=False
        )

        self.bn1 = nn.BatchNorm2d(out_channels)

        self.conv2 = nn.Conv2d(
            out_channels,
            out_channels,
            kernel_size=3,
            padding=1,
            bias=False
        )

        self.bn2 = nn.BatchNorm2d(out_channels)

        self.shortcut = nn.Sequential()

        if stride != 1 or in_channels != out_channels:

            self.shortcut = nn.Sequential(
                nn.Conv2d(
                    in_channels,
                    out_channels,
                    kernel_size=1,
                    stride=stride,
                    bias=False
                ),
                nn.BatchNorm2d(out_channels)
            )

    def forward(self, x):

        out = torch.relu(self.bn1(self.conv1(x)))

        out = self.bn2(self.conv2(out))

        out += self.shortcut(x)

        out = torch.relu(out)

        return out

# ============================================================
# 7. BOTTLENECK ORDERED RESNET18
# ============================================================

class BottleneckResNet18(nn.Module):

    def __init__(self, channels, num_classes=10):

        super().__init__()

        c1, c2, c3, c4 = channels

        self.in_channels = c1

        self.conv1 = nn.Conv2d(
            3,
            c1,
            kernel_size=3,
            stride=1,
            padding=1,
            bias=False
        )

        self.bn1 = nn.BatchNorm2d(c1)

        self.layer1 = self._make_layer(c1, 2, stride=1)
        self.layer2 = self._make_layer(c2, 2, stride=2)
        self.layer3 = self._make_layer(c3, 2, stride=2)
        self.layer4 = self._make_layer(c4, 2, stride=2)

        self.pool = nn.AdaptiveAvgPool2d((1,1))

        self.fc = nn.Linear(c4, num_classes)

    def _make_layer(self, out_channels, blocks, stride):

        layers = []

        strides = [stride] + [1]*(blocks-1)

        for s in strides:

            layers.append(
                BasicBlock(
                    self.in_channels,
                    out_channels,
                    s
                )
            )

            self.in_channels = out_channels

        return nn.Sequential(*layers)

    def forward(self, x, return_features=False):

        feats = []

        out = torch.relu(self.bn1(self.conv1(x)))
        feats.append(out)

        out = self.layer1(out)
        feats.append(out)

        out = self.layer2(out)
        feats.append(out)

        out = self.layer3(out)
        feats.append(out)

        out = self.layer4(out)
        feats.append(out)

        pooled = self.pool(out)

        pooled = pooled.view(pooled.size(0), -1)

        logits = self.fc(pooled)

        if return_features:
            return logits, feats

        return logits

# ============================================================
# 8. CONFIGURATIONS
# ============================================================

configs = {

    "Progressive": [32, 64, 128, 256],

    "Regressive": [256, 128, 64, 32],

    "Uniform": [64, 64, 64, 64]
}

# ============================================================
# 9. TRAINING
# ============================================================

def train_model(model, trainloader, epochs=EPOCHS):

    model.to(device)

    criterion = nn.CrossEntropyLoss()

    optimizer = optim.Adam(
        model.parameters(),
        lr=LR
    )

    for epoch in range(epochs):

        model.train()

        running_loss = 0

        correct = 0
        total = 0

        loop = tqdm(trainloader)

        for images, labels in loop:

            images = images.to(device)
            labels = labels.to(device)

            optimizer.zero_grad()

            outputs = model(images)

            loss = criterion(outputs, labels)

            loss.backward()

            optimizer.step()

            running_loss += loss.item()

            _, predicted = outputs.max(1)

            total += labels.size(0)

            correct += predicted.eq(labels).sum().item()

            acc = 100 * correct / total

            loop.set_description(
                f"Epoch {epoch+1} "
                f"Loss {running_loss:.2f} "
                f"Acc {acc:.2f}%"
            )

    return model

# ============================================================
# 10. EVALUATION
# ============================================================

def evaluate(model, testloader):

    model.eval()

    correct = 0
    total = 0

    with torch.no_grad():

        for images, labels in testloader:

            images = images.to(device)
            labels = labels.to(device)

            outputs = model(images)

            _, predicted = outputs.max(1)

            total += labels.size(0)

            correct += predicted.eq(labels).sum().item()

    return 100 * correct / total

# ============================================================
# 11. CKA
# ============================================================

def gram(x):

    return x @ x.T

def center(g):

    n = g.size(0)

    H = torch.eye(n, device=g.device) \
        - torch.ones(n,n,device=g.device)/n

    return H @ g @ H

def cka(x, y):

    x = x.flatten(1)
    y = y.flatten(1)

    K = center(gram(x))
    L = center(gram(y))

    return (K*L).sum() / (
        torch.norm(K)*torch.norm(L)
    )

# ============================================================
# 12. COMPUTE CKA MATRIX
# ============================================================

def compute_cka_matrix(model, loader):

    model.eval()

    images, _ = next(iter(loader))

    images = images.to(device)

    _, acts = model(images, return_features=True)

    acts = [a.mean(dim=[2,3]) for a in acts]

    n = len(acts)

    mat = torch.zeros(n,n)

    for i in range(n):

        for j in range(n):

            mat[i,j] = cka(acts[i], acts[j]).item()

    return mat

# ============================================================
# 13. FEATURE VISUALIZATION
# ============================================================

def visualize_features(model, loader, title):

    model.eval()

    images, _ = next(iter(loader))

    images = images.to(device)

    _, acts = model(images[:1], return_features=True)

    for i, act in enumerate(acts):

        fmap = act[0].detach().cpu()

        plt.figure(figsize=(12,2))

        for j in range(min(8, fmap.shape[0])):

            plt.subplot(1,8,j+1)

            plt.imshow(fmap[j], cmap='viridis')

            plt.axis('off')

        plt.suptitle(f"{title} - Layer {i+1}")

        plt.show()

# ============================================================
# 14. PCA REPRESENTATION ANALYSIS
# ============================================================

def pca_analysis(model, loader, title):

    model.eval()

    images, _ = next(iter(loader))

    images = images.to(device)

    _, acts = model(images, return_features=True)

    feat = acts[-1]

    feat = feat.mean(dim=[2,3])

    feat = feat.detach().cpu().numpy()

    pca = PCA(n_components=2)

    reduced = pca.fit_transform(feat)

    plt.figure(figsize=(6,6))

    plt.scatter(
        reduced[:,0],
        reduced[:,1],
        s=10
    )

    plt.title(f"PCA Representation: {title}")

    plt.xlabel("PC1")
    plt.ylabel("PC2")

    plt.show()

# ============================================================
# 15. RUN EXPERIMENTS
# ============================================================

trainloader, testloader, num_classes = get_dataloaders(DATASET)

results = {}

trained_models = {}

for name, channels in configs.items():

    print("\n===================================")
    print("Training:", name)
    print("===================================")

    model = BottleneckResNet18(
        channels,
        num_classes=num_classes
    )

    model = train_model(model, trainloader)

    acc = evaluate(model, testloader)

    results[name] = acc

    trained_models[name] = model

    print(f"{name} Accuracy: {acc:.2f}%")

# ============================================================
# 16. ACCURACY COMPARISON
# ============================================================

plt.figure(figsize=(8,5))

plt.bar(
    list(results.keys()),
    list(results.values())
)

plt.ylabel("Accuracy (%)")

plt.title(
    f"{DATASET.upper()} Accuracy Comparison"
)

plt.show()

# ============================================================
# 17. CKA ANALYSIS
# ============================================================

for name, model in trained_models.items():

    print(f"\nCKA Analysis: {name}")

    cka_matrix = compute_cka_matrix(
        model,
        testloader
    )

    plt.figure(figsize=(6,5))

    sns.heatmap(
        cka_matrix.numpy(),
        annot=True,
        cmap='viridis',
        vmin=0,
        vmax=1
    )

    plt.title(f"CKA Similarity - {name}")

    plt.xlabel("Layer")
    plt.ylabel("Layer")

    plt.show()

# ============================================================
# 18. FEATURE VISUALIZATION
# ============================================================

for name, model in trained_models.items():

    print(f"\nFeature Visualization: {name}")

    visualize_features(
        model,
        testloader,
        name
    )

# ============================================================
# 19. PCA ANALYSIS
# ============================================================

for name, model in trained_models.items():

    print(f"\nPCA Analysis: {name}")

    pca_analysis(
        model,
        testloader,
        name
    )

# ============================================================
# 20. FINAL RESULTS TABLE
# ============================================================

print("\n===================================")
print("FINAL RESULTS")
print("===================================")

print(f"{'Model':20s} Accuracy")

for k, v in results.items():

    print(f"{k:20s} {v:.2f}%")